package:
  name: "conda-libmamba-solver"
  version: "{{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}"

source:
  # git_url is nice in that it won't capture devenv stuff.  However, it only
  # captures committed code, so pay attention.
  git_url: ../
  folder: src/

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install src/ -vv --no-deps --no-build-isolation"

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.9
    - conda >=24.11
    - libmambapy >=2.0.0
    - boltons >=23.0.0

test:
  imports:
    - conda_libmamba_solver
  commands:
    - conda create -n test --dry-run scipy --solver=libmamba
    - >-
      python -c
      "import conda_libmamba_solver as cls;
      from importlib.metadata import version;
      assert '{{ PKG_VERSION }}' == cls.__version__ == version('conda_libmamba_solver'),
      '{{ PKG_VERSION }}' + f', {cls.__version__}, ' + version('conda_libmamba_solver')
      " || true
    # we accept errors here because GIT_DESCRIBE_TAG has some accuracy issues.
    # Shouldn't happen in production recipes; aka do not add '|| true' in the feedstock

about:
  home: https://github.com/conda/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: 'The fast mamba solver, now in conda!'

extra:
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
