name: Docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "docs/**"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: conda-incubator/setup-miniconda@9f54435e0e72c53962ee863144e47a4b094bfd35 # v2.3.0
        with:
          activate-environment: conda-libmamba-solver
          environment-file: docs/environment.yml
          python-version: '3.11'
          auto-activate-base: false

      - name: Build Documentation
        run: |
          cd docs
          make dirhtml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          # Upload entire repository
          path: 'docs/_build/dirhtml'

  pages:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [docs]

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
